### ISSUE TITLE
Create an api for user registration and login with jwt authentication

### ISSUE THREAD

**Issue by WesGtoX** [Hacksbr/resume#4]
## Recommendations

- [ ] Library recommends to use [Simple JWT](https://django-rest-framework-simplejwt.readthedocs.io/en/latest/)
- [ ] Use [Poetry](https://python-poetry.org/docs/)
- [ ] Perform tests

#### `POST /api/v1/register/`
```json
{
  "email": "String",
  "password: "String"
}
```

##### Return:
```json
{}
```

#### `POST /api/v1/login`
```json
{
  "username": "String",
  "password: "String"
}
```

##### Return:
```json
{
  "token": "String",
  "refresh token": "String"
}
```

**Comment by HenryZerocool** [comment]
Hi, can I try this issue?

**Comment by WesGtoX** [comment]
@HenryZerocool yes, you can, thank you!
